json.id resource.id
json.name resource.name
json.color resource.color
json.availability resource.availability
json.inbox_ids resource.inbox_ids
json.work_channels resource.work_channels
json.position resource.position
json.active resource.active
json.offline_after_seconds resource.offline_after_seconds
json.offline_to_status_id resource.offline_to_status_id
json.counts_as_online resource.counts_as_online
